object = {
  0: "Hammer",
  1: "SSD",
  2: "Alcohol",
  3: "Spanner",
  4: "Axe",
  5: "Awl",
  6: "Throwing Knife",
  7: "Firecracker",
  8: "Thinner",
  9: "Plier",
  10: "Match",
  11: "Smart Phone",
  12: "Scissors",
  13: "Tablet PC",
  14: "Solid Fuel",
  15: "Bat",
  16: "Portable Gas",
  17: "Nail Clippers",
  18: "Knife",
  19: "Metal Pipe",
  20: "Electronic Cigarettes(Liquid)",
  21: "Supplymentary Battery",
  22: "Bullet",
  23: "Gun Parts",
  24: "USB",
  25: "Liquid",
  26: "Aerosol",
  27: "Screwdriver",
  28: "Chisel",
  29: "Handcuffs",
  30: "Lighter",
  31: "HDD",
  32: "Electronic Cigarettes",
  33: "Battery",
  34: "Gun",
  35: "Laptop",
  36: "Saw",
  37: "Zippo Oil",
  38: "Stun Gun",
  39: "Camera",
  40: "Camcorder",
  41: "SD Card",
}